name: 'aether_emulator_project'
description: 'A sample command-line application.'
version: '0.0.0'
repository: 'https://github.com/AetherEmulator/AetherEmulator'
homepage: 'https://github.com/AetherEmulator/AetherEmulator'
issue_tracker: 'https://github.com/AetherEmulator/AetherEmulator/issues'
documentation: 'https://github.com/AetherEmulator/AetherEmulator/tree/main/docs'
funding:
  - 'https://github.com/sponsors/AetherEmulator'
  - 'https://github.com/sponsors/AetherEmulator' 
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  general_lib: '^0.0.49'
  mason_logger: '^0.3.1'
  packagex: '^0.0.64'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.2'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.0'
dev_dependencies:
  lints: '^4.0.0'
  test: 'any'
publish_to: 'none'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
